
// SIN RETURN
function mi_primer_algoritmo(){
    var mensaje = "Hola Mundo";
    alert (mensaje);
}
function decimalBinario(binario){
var decimal = 0
for (let i =0;i < binaro.lenght; i++){
    digitobinario = binario[i];
    if(digitobinario==='1'){
        decimal = decimal * 2 + 1;
    }
    else{

        decimal = decimal * 2 + 0
    }

}

alert(decimal);

}

function sumaPrimos(){


}
//CON